# Generated by Django 4.1.2 on 2022-10-30 07:09

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=400)),
                ('foto', models.ImageField(default='nofoto.jpg', null=True, upload_to='static/img/fotografos')),
            ],
            options={
                'verbose_name_plural': 'Albumes',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 9, 11, 567113))),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('cartel', models.CharField(blank=True, max_length=250, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('distancia', models.IntegerField(blank=True, null=True)),
                ('precio', models.CharField(blank=True, max_length=50, null=True)),
                ('destacada', models.BooleanField(default=True)),
                ('texto', ckeditor.fields.RichTextField(blank=True, max_length=99999999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='static/img/imagenes/nofoto.jpg', upload_to='./static/img/imagenes')),
                ('tipo', models.IntegerField(choices=[(1, 'cartel'), (2, 'post'), (3, 'varios'), (4, 'patrocinador')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', ckeditor.fields.RichTextField(blank=True, max_length=99999999, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.FileField(upload_to='./static/resultados')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 9, 11, 570112))),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Puntuaciones',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cartel', models.CharField(blank=True, max_length=250, null=True)),
                ('texto', ckeditor.fields.RichTextField(max_length=99999999)),
                ('fecha_publicacion', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 8, 9, 11, 566109), null=True)),
                ('visible', models.BooleanField(default=True)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.imagen')),
                ('seccion', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cartel', models.CharField(blank=True, max_length=250, null=True)),
                ('texto', ckeditor.fields.RichTextField(max_length=99999999)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', ckeditor.fields.RichTextField(blank=True, max_length=99999999, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('Caducada', models.BooleanField(default=False)),
                ('p_carrera_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.CharField(blank=True, max_length=9999, null=True)),
                ('detalles', models.CharField(blank=True, max_length=9999, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=9999)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 9, 11, 569112))),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.imagen'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='provincia',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.provincia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='resultado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.resultado'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carmona.tipo'),
        ),
    ]
