# Generated by Django 4.1.2 on 2022-10-30 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 19, 50, 290392)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 19, 50, 291391)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 8, 19, 50, 289391), null=True),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 8, 19, 50, 292391)),
        ),
    ]
